sudo: required
dist: trusty
language: ruby
cache: bundler
addons:
  firefox: latest
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
script:
  - 'bundle exec rake rubocop'
  - 'bundle exec rails test'
  - 'bundle exec rails test:system'
