defaults: &defaults
  api_host: https://api.opensuse.org
  web_host: https://build.opensuse.org
  api_username: <%= ENV['API_USERNAME'] %>
  api_password: <%= ENV['API_PASSWORD'] %>
  relative_url_root:
development:
  <<: *defaults
test:
  <<: *defaults
  opensuse_cookie: TEST
production:
  <<: *defaults
  relative_url_root:
  api_username: <%= ENV['API_USERNAME'] %>
  api_password: <%= ENV['API_PASSWORD'] %>
  use_static: software.o.o
  opensuse_cookie: <%= ENV['OPENSUSE_COOKIE'] %>
